### ISSUE TITLE
Support for multiple networks in watershed

### ISSUE THREAD

**Issue by KellyMWhitehead** [SouthForkResearch/gnat#1]
Support of working with multiple networks (disconnected) in one watershed. 

# Proposals
1. This could be accomplished through a NetworkID field with one INT per network. 
2. A Network look up table could store the Downstream FID for each network, but must be careful of modified FID's during processing. Alternatively network could contain an IsOutlet or similarly named boolean field.
3. Downprocess tools would need to be modified to support the use of this enhancement, likely through a simple looping algorithm.

**Comment by jesselangdon** [comment]
This functionality should be implemented in the osGNAT, and not the ESRI version of this tool.
