### ISSUE TITLE
GNAT.pyt needs to be cleaned up

### ISSUE THREAD

**Issue by jesselangdon** [SouthForkResearch/gnat#17]
Currently the GNAT.pyt file has a lot of commented out modules import statements, and unused modules.  Needs to be cleaned up.

**Comment by KellyMWhitehead** [comment]
Jesse, I have a local branch where I have started cleaning this up.

I will push it to the main dev branch soon.

**Comment by jesselangdon** [comment]
Cleaned up unused classes and modules.
