### ISSUE TITLE
Error rerunning Find Network Features tool after one initial round of preprocess

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/gnat#19]
Steps: Went through the Build Stream Network and Find Network Features process once. Joined the table to the processed stream network layer, found and fixed errors, unjoined the table, then tried to rerun the process to check again for any residual errors. Build Stream Network worked this second time around to create a new stream network feature class with two timestamps, es expected. However, running the Find Network Features tool yielded this error and warning in the last lines of messages:

>Error 000732 : Input features: Dataset C:\ISEMP\Networks\UpperSalmon\_2Preprocess\Preprocess.gdb\UpperSalmon_EP_2017202_201702021559_201702060939 does not exist or is not supported.
>Warning 000725: Output Layer: Dataset in network_fc_lyr already exists.
>Failed to execute (MakeLayerFeature).
>Failed to execute (FindNetworkFeaturesTool).

**Comment by jesselangdon** [comment]
I was unable to recreate this error. Moving the tables and feature classes to a new file geodatabase seemed to help Arielle
