### ISSUE TITLE
Sinuosity Tool Shapefiles Error

### ISSUE THREAD

**Issue by KellyMWhitehead** [SouthForkResearch/gnat#2]
There is an arcgis bug that is preventing shapefiles to work with the sinuosity tool.

Need to modify how the features are tracked without using OID/FID to remedy this.

**Comment by jesselangdon** [comment]
Fixed this a part of responding to Issue #14 .  The tool now creates a temporary stream network feature class, creates temporary ID fields to do internal joining.
