### ISSUE TITLE
segmentation error (?)

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/gnat#26]
I've gotten this 'failed to execute' result from all the segmentation runs I've done--here's a screenshot.  It seems like it does segment and the script seems to go through until the end, but the failed to execute also appears.

I can provide the network tomorrow as well.
![untitled](https://cloud.githubusercontent.com/assets/13526689/25111031/63e16e8e-239d-11e7-9043-5f42df20db9e.png)

**Comment by KellyMWhitehead** [comment]
This is a stream order issue. I need to look at the data to see where the network is causing the issue. I am very surprised if the segmentation is successful (this happens after stream order/branches are calculated). Maybe you are looking at the existing reaches in the network?

**Comment by jesselangdon** [comment]
This was a stream network that wasn't fully cleaned.
