### ISSUE TITLE
Issue with Segmentation tool

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/gnat#30]
Both arcGNAT_2.1.01_050317 and arcGNAT_2.1.03_beta are having an issue where the repaired stream network will not load into the tool (as either a feature class or a shapefile) in the Stream Network Polyline Feature Class input.

Also I am not able to get anything to fill out under Output Segmented Line Network when I try to save the output (possibly due to the loading issue); it only allows me to try to save the output as a Geodatabase or a Basic Type, when I am trying to output a feature class into a new geodatabase.

![screenshot 2017-05-05 16 11 07](https://cloud.githubusercontent.com/assets/25061462/25970222/af356e78-364c-11e7-9a2d-6ff83e61942a.png)

**Comment by KellyMWhitehead** [comment]
Fixed in 078083ebf0976a7f06a6660601f82ab8cad5ad6f
