### ISSUE TITLE
Need better handling of transferred attribute values in cases with missing values

### ISSUE THREAD

**Issue by jesselangdon** [SouthForkResearch/gnat#31]
If there are stream features in the "To" dataset that do not exist in the "From" dataset, all of the values in the "To" dataset have Nulls or zeros in the transferred attribute fields.  These should instead all be something like -99999 for numeric fields, and "-99999" for string fields.

**Comment by KellyMWhitehead** [comment]
Jesse, has this been implemented?

**Comment by jesselangdon** [comment]
Yes.

**Comment by KellyMWhitehead** [comment]
I am going to close this issue and put out a testing release.

**Comment by jesselangdon** [comment]
Sounds good!
