### ISSUE TITLE
Transfer Line Attributes Issue - failed joins in cross pattern across watershed

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/gnat#32]
During a test run for the Walla Walla watershed, I tested the TLA Tool to have it transfer between the NHD EP Extent layer generated by Jean on 12/2/2016 to the NHD Flowline digitized 4/22/17 and then vice versa. Both are shapefiles projected into North America Albers Equal Area Conic. 

In both tests (both directions), I had about 180/14,180 segments in the network fail to join and fail to have the attributes transfer. Aka attributes were not transferred (contain ‘null’ values), and there are null values in the output layer fields “Join_Count”, “TARGET_FID”, “JOIN_FID”, and “Shape_Length_1”. The attribute information from the original "TO" layer is retained, and the new “Shape_Length” field is filled out.

They formed an odd "cross" shape through the middle of the watershed. The data is present in the Dropbox folder below. The original layers used are
NHDFlowline: "NHDFlowline_copy.shp"
NHD_EPExtent: "WallaWalla_NHD_FullExtent_copy.shp"
Outputs: TransferLineAttributes.gdb > "WallaWalla_EPtoNHD", "WallaWalla_NHDtoEP"
https://www.dropbox.com/home/Transfer%20Line%20Attributes%20Tool%20QC

![image](https://cloud.githubusercontent.com/assets/25061462/26376578/db531752-3fc1-11e7-8e96-96f16a0d18b9.png)

**Comment by jesselangdon** [comment]
When the "From" dataset is buffered, it was being split into four different "quadrants" despite the fact that the parameters for the buffer tool were set to 'dissolve all'.  So I added an additional Dissolve process immediately after.  This seems to have solved the issue.

See commit https://github.com/SouthForkResearch/gnat/commit/5647d4549187cad0b31d13b374c3b0e94b409587
