### ISSUE TITLE
Find Network Features tool not detecting small gaps in network

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/gnat#36]
Small gaps (~20cm) in the network that are disconnected pass through the Network Errors tool without being detected. 

Please see attached zip with:
1) Geodatabase: has the segmented (1000m) network for Lolo watershed. It was run twice through the Build Network Topology and Find Network Features tools (corresponds to run01 and run02 feature classes, respectively) and the Stream Network and Network Features tables and Network Vertex layer link to run02.
2) mxd: Has bookmarks corresponding to the locations of all the small gaps that were detected using the FLoWs tool in checking for compatibility of the network with HexSim.

[Lolo.zip](https://github.com/SouthForkResearch/gnat/files/1089778/Lolo.zip)

**Comment by jesselangdon** [comment]
This issue was (hopefully) improved with changes made in this commit:
https://github.com/SouthForkResearch/gnat/commit/808959c4ee369179dfc0c70b68591e1b1b0b5750
