### ISSUE TITLE
Transfer Line Attributes creates -99999 values for segments with same geometry; related to failure?

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/gnat#37]
Tested the Transfer Line Attributes tool for the Lolo watershed network from Jean's EP layer (“Lolo_NHD_FullExtent_20160906.shp”) to the NHDFlowline from the NHD website.

1.	Generate New Lolo Network by running Transfer Line Attributes for Lolo network only.
a.	Clip NHD_Flowline to CHaMP watershed (Lolo) boundary; make sure to extent the most downstream segment out beyond the watershed as it is in Jean’s layer and in original NHDFlowline.
i.	Output: “NHDFlowline_20170502_Lolo”
b.	Run the TLA Tool.
i.	FROM: “Lolo_NHD_FullExtent_20160906.shp”
ii.	TO: “NHDFlowline_20170502_Lolo.shp”
iii.	OUTPUT: “Lolo_EPtoNHD_20170621” 
1.	Output sent as a feature class to a geodatabase.
c.	TLA Failure, with products created.

2.	Examine the segments that did not join (received -9999 values)
a.	Seems that in all these areas Jean’s layer has segments split into multiple segments whereas the NHDFlowline has only one segment. Perhaps issue is that attribute values should be identical between these split segments, but in some cases CHINRATE and STHDRATE have different values between segments?
i.	This does not appear to be causing issues (when values are different in Jeans layer between segments that should be the same in NHD layer) based on other areas in the data where NHDFlowline had one segment and Jean's layer has multiple segments with slightly different attribute values (for non-essential fields)
b.	Only issue I can see is geometry is the same but segment lengths differ.
i.	Uncertain if failure message is related to this or not.

Data:
https://www.dropbox.com/s/qb9tl6oqrysr9r4/TLA_Issue_Lolo.zip?dl=0
Failure message:
![screenshot 2017-06-21 13 30 44](https://user-images.githubusercontent.com/25061462/27407168-3832ee44-568c-11e7-8794-39991d309d75.png)

**Comment by aagervasi** [comment]
I received this same error message running the TLA on the Middle Fork Clearwater error. Appears to be systematic. Any thoughts on what might be causing it?


![screenshot 2017-07-10 13 37 04](https://user-images.githubusercontent.com/25061462/28038836-104b8f06-6575-11e7-82b6-059a35d04ead.png)

**Comment by aagervasi** [comment]
Actually this may be more than just a simple error and relate more to when the networks do not have the same geometry. 

**See below** I edited the EP layer (the NHD layer with anadromous data added, in green) to extend the segments out where they had initially been cut off at the HUC8 boundaries to match the NHDFlowline, (purple). After I did this and re-ran the tool, the tool ran successfully. So the error message may just be due to when it finds places in the networks that are non-identical.

Before:
![mfclearwater_1](https://user-images.githubusercontent.com/25061462/28039900-b4940dce-6578-11e7-94f4-8748e226e810.png)
After:
![mfclearwater_2](https://user-images.githubusercontent.com/25061462/28039899-b493b89c-6578-11e7-83dd-8871ffdb6512.png)

**Comment by jesselangdon** [comment]
Fixed this issue, as well as an issue I found associated with the wrong records being transferred (due to joining based on OIDs).

See this commit for details:
https://github.com/SouthForkResearch/gnat/commit/d527db9a434d88c2428a1e0ec4e32ece67fe7d77
