### ISSUE TITLE
The main() function for the StreamTool accepts the wrong number of outputs

### ISSUE THREAD

**Issue by banderson1618** [SouthForkResearch/gnat#41]
The tool accepts three output names, but it only has two in the main function, which leads to the third output name overwriting the name of the scratch workplace. This breaks the program fairly quickly. While looking through GNAT.pyt, I saw that the text for properly passing on all variables was commented out. I'm not certain why they were commented out, but, after modifying it to only take two output files, I managed to get it to run properly. If you'd like, I can send you the code with the fixes that I made.

**Comment by jesselangdon** [comment]
I'm not sure which tool you are referring to ("StreamTool"?).  Do you mean the **Calculate Stream Order**?  Can you send me the specific error that you're encountering? Thanks.

**Comment by banderson1618** [comment]
I do mean Calculate Steam Order, sorry for the confusion.

The error that I received was in gis_tools.py, line 44,  "Local variable
'ext' referenced before assignment"

This error appears because 'ext' is only defined if 'workspace' exists.
'Workspace' doesn't exist because the tool is passing in the first 5
arguments given to it, but asks for 6. The last input, Scratch workspace,
is overwritten by the 5th input, "Output Junction points".

If you have further questions, feel free to ask. Trying to explain code
errors over email is a bit tricky. I can send you my solutions, if you'd
like.

**Comment by jesselangdon** [comment]
Hi Braden. Is it possible for you to send the entire original error
message? Thanks.

**Comment by banderson1618** [comment]
Traceback (most recent call last):
   File "<string>", line 1039, in execute
   File
"C:\Users\A02150284\Documents\ArcGIS\AddIns\Desktop10.5\GNAT\StreamOrder.py",
line 45, in main
      fcNetworkDissolved = gis_tools.newGISDataset(scratchWorkspace,
"GNAT_SO_NetworkDissolved")
   File
"C:\Users\A02150284\Documents\ArcGIS\AddIns\Desktop10.5\GNAT\gis_tools.py",
line 44, in newGISDataset
      inputDataset = workspace + "\\" + inputDatasetName + ext
   UnboundLocalError: local variable 'ext' referenced before assignment

  Failed to execute (StreamOrderTool)

**Comment by jesselangdon** [comment]
Remove junction points output parameter (forgot to earlier I guess)...
See commit: 
https://github.com/SouthForkResearch/gnat/commit/f99854a2a5b01ee3712e04ce675213fd71f2d6a2
