### ISSUE TITLE
Non-urgent: Commit Stream Network Script does not display fields in drop-down

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/gnat#42]
After Creating a new GNAT Project and Loading the Input Data Sets, when I select the Stream Network shapefile from the GNAT Riverscapes project folder, the drop-down is blank. It will work correctly and run through Segmentation; I just have to manually type in "ReachID" as the Unique ID field.

![screenshot 2017-08-09 11 13 24](https://user-images.githubusercontent.com/25061462/29138821-a7c81444-7cf9-11e7-9be8-3166e9750e78.png)
![screenshot 2017-08-09 11 13 39](https://user-images.githubusercontent.com/25061462/29138820-a7c72412-7cf9-11e7-8e6f-032ea6b3948d.png)

Data:
https://www.dropbox.com/home/Riverscapes_share/Lochsa_Data

(Original Stream Network used for the commitment is the run02 network from the Preprocess.gdb--all Riverscapes data is inside the GNAT Riverscapes folder)

**Comment by jesselangdon** [comment]
Fixed this in GNAT.pyt.  See this commit:
https://github.com/SouthForkResearch/gnat/commit/e18025765ee44e3c42fbf8c414e22b67a129239e
